
tasks:
  # - init: go get && go build ./... && go test ./...
  - init: |
      sudo apt install pgcli -y
      alias d='docker'
      alias dc='docker-compose'
      mkdir -p ~/.config/fish/functions
      printf "function d\n  docker \$argv;\nend\n" > ~/.config/fish/functions/d.fish
      printf "function dc\n  docker-compose \$argv;\nend\n" > ~/.config/fish/functions/dc.fish
      docker network create auth_proxy_network
      go get
    
    # command: go run

ports:
  - port: 4400
    visibility: public
    onOpen: ignore
  - port: 5432
    visibility: public
    onOpen: ignore
  - port: 1025
    visibility: public
    onOpen: ignore
  - port: 8025
    visibility: public
    onOpen: ignore
  - port: 8000
    visibility: public
    onOpen: ignore

vscode:
  extensions:
    - mikestead.dotenv