
tasks:
  - before: |
      echo "before-------------------------"
      sudo apt install pgcli -y
      echo '-----------------------------'
      go get
      echo '-----------------------------'
      docker network create auth_proxy_network
      echo '-----------------------------'
      alias d='docker'
      alias dc='docker-compose'
      echo '-----------------------------'
      mkdir -p ~/.config/fish/functions
      printf "function d\n  docker \$argv;\nend\n" > ~/.config/fish/functions/d.fish
      printf "function dc\n  docker-compose \$argv;\nend\n" > ~/.config/fish/functions/dc.fish
      echo "end before-------------------------"

  - init: |
      echo "init-------------------------"
    
    # command: go run

ports:
  - port: 4400
    visibility: public
    onOpen: ignore
  - port: 5432
    visibility: public
    onOpen: ignore
  - port: 1025
    visibility: public
    onOpen: ignore
  - port: 8025
    visibility: public
    onOpen: ignore
  - port: 8000
    visibility: public
    onOpen: ignore

vscode:
  extensions:
    - mikestead.dotenv