version: '3.1'

services:

  db:
    image: postgres
    container_name: auth-db-dev
    restart: always
    ports:
      - 5432:5432
    volumes:
      - "./pgdata:/var/lib/postgresql/data/pgdata"
      - "./migrations:/dumps"
      - "./etc/.pgpass:/root/.pgpass"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: auth 
      PGDATA: /var/lib/postgresql/data/pgdata


  node:
    image: "node:alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./test_apps:/home/node/app
    expose:
      - "3001"
      - "3002"
    ports:
      - 3001:3001
      - 3002:3002
    command: "npm run start12"


