FROM ubuntu:18.04
#FROM debian:stable-slim
LABEL maintainer="RGRU <ivlev@rg.ru>"

RUN apt-get -y update && apt-get -y install sshpass 

COPY configs  /app/configs
COPY migrations  /app/migrations
COPY templates  /app/templates
COPY docs  /app/docs

COPY auth-proxy  /app/auth

EXPOSE 4400

CMD bash -c "cd /app && ./auth -serve 4400 -env=docker"




