FROM alpine:latest


RUN apk update
RUN apk add --update bash && rm -rf /var/cache/apk/*
RUN apk add libc6-compat
RUN apk --no-cache add ca-certificates
# set local date to Europe/Moscow
RUN apk add --no-cache tzdata
RUN cp /usr/share/zoneinfo/Europe/Moscow /etc/localtime
RUN apk add curl
# RUN apk add iputils-ping

COPY auth-proxy     /app/auth-proxy
COPY configs        /app/configs
COPY migrations     /app/migrations
COPY templates      /app/templates
COPY etc            /app/etc
COPY certificates   /app/certificates
COPY admin          /app/admin


WORKDIR /app
CMD ./auth-proxy -port=4400 -config=./configs/app.env.public -pgconfig=./configs/db.env.public

EXPOSE 4400