# !!!!! Этот файл используется для разработки auth-proxy
# Должен быть запущен до запуска программы

version: '3.5'

services:

  # серивис базы данных
  auth-db:
    image: postgres:10.9-alpine
    container_name: auth-db-dev
    restart: always
    ports:
      - 5432:5432
    volumes:
      - "./pgdata:/var/lib/postgresql/data/pgdata"
    #   - "./migrations:/dumps"
    #   - "./etc/.pgpass:/root/.pgpass"
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: 159753
      POSTGRES_DB: rgru
      PGDATA: /var/lib/postgresql/data/pgdata

  # сервис тестирования отправки почты
  auth-mail:
    image: mailhog/mailhog
    container_name: auth-mail-dev
    ports:
      - 1025:1025
      - 8025:8025


# внешняя сеть добавлена, чтобы можно было проксировать или обращаться к приложениям по именам служб,
# прописанных в файлах docker-compose.yml этих приложений, если конечно эти приложения так же
# входят в подсеть auth_proxy_network.
#  В противном случае придётся прописывать IP адреса приложений,
# что неудобно при переносе приложений или их перезапуске.
networks:
  default:
    name: auth_proxy_network
