version: '3.1'

services:

  auth-db:
    image: postgres:10.9-alpine
    container_name: auth-db-dev
    restart: always
    ports:
      - 5432:5432
    # volumes:
    #   - "./pgdata:/var/lib/postgresql/data/pgdata"
    #   - "./migrations:/dumps"
    #   - "./etc/.pgpass:/root/.pgpass"
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: 159753
      POSTGRES_DB: rgru 
      PGDATA: /var/lib/postgresql/data/pgdata



# внешняя сеть добавлена, чтобы можно было проксировать или обращаться к приложениям по именам служб,
# прописанных в файлах docker-compose.yml этих приложений, если конечно эти приложения так же 
# входят в подсеть auth_proxy_network.
#  В противном случае придётся прописывать IP адреса приложений, 
# что неудобно при переносе приложений или их перезапуске. 
networks:
  default:
    external: true
    name: auth_proxy_network    
