version: '3.1'

services:

  # сервер, где запущено приложение
  auth-proxy-front:
    image: rgru/auth-proxy:latest
    container_name: auth-proxy-front
    restart: unless-stopped
    # параметры подсоединения к Postgres могут быть указаны в файле или в переменных
    # environment:
    #   - PG_HOST=postgres
    #   - PG_USER=pgadmin
    #   - PG_PASSWORD=159753
    #   - PG_DATABASE=rgru
    #   - PG_PORT=5432
    #   - PG_SEARCH_PATH=auth,extensions
    #   - PG_SSLMODE=disable      
    # env_file:
    #   - ./db.env
    ports:
      - 4400:4400
    depends_on:
      - postgres
    # command: bash -c "cd /app && ./auth -serve 4400 -env=front" 
  


  # база данных Postgres 
  postgres:
    image: postgres:10.9-alpine
    container_name: postgres
    restart: unless-stopped
    # ports:
    #   - 5432:5432
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: 159753
      POSTGRES_DB: rgru 
      PGDATA: /var/lib/postgresql/data/pgdata
  


# внешняя сеть добавлена, чтобы можно было проксировать или обращаться к приложениям по именам служб,
# прописанных в файлах docker-compose.yml этих приложений, если конечно эти приложения так же 
# входят в подсеть auth_proxy_network.
#  В противном случае придётся прописывать IP адреса приложений, 
# что неудобно при переносе приложений или их перезапуске. 
networks:
  default:
    external:
      name: auth_proxy_network    