version: '3.1'

services:

  # сервер, где запущено приложение
  auth-proxy-front:
    # image: rgru/auth-proxy:latest
    image: registry.rgwork.ru:5050/masterback/auth-proxy/auth-proxy:dev
    container_name: auth-proxy-front
    restart: unless-stopped
    ports:
      - 4400:4400
    depends_on:
      - postgres
      
    # Параметры подсоединения к Postgres могут быть указаны в файле 
    # env_file:
    #   - ./my_db.env

    # Параметры подсоединения к Postgres могут быть указаны в переменных
    # environment:
    #   - PG_HOST=postgres
    #   - PG_USER=pgadmin
    #   - PG_PASSWORD=159753
    #   - PG_DATABASE=rgru
    #   - PG_PORT=5432
    #   - PG_SEARCH_PATH=auth,extensions
    #   - PG_SSLMODE=disable   
    #   - PG_REFRESH_TIME=4   
    # Тогда необходимо запустить программу с параметром -pg-params-from-os.   
    # command: bash -c "cd /app && ./auth -port 4400 -env=front -pg-params-from-os" 
    
    # Конфигурационный файл Postgres может быть задан явно 
    # и через параметр командной строки -pgconfig
    # command: bash -c "cd /app && ./auth -port 4400 -env=front -pgconfig=shared_dir/my_db.env" 
  


  # база данных Postgres 
  postgres:
    image: postgres:10.9-alpine
    container_name: postgres
    restart: unless-stopped
    # ports:
    #   - 5432:5432
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: 159753
      POSTGRES_DB: rgru 
      PGDATA: /var/lib/postgresql/data/pgdata
  
  # сервис тестирования отправки почты
  # Письма смотреть по адресу: http://localhost:8025/
  auth-mail:
    image: mailhog/mailhog
    container_name: auth-mail-dev
    ports:
      - 1025:1025
      - 8025:8025


# внешняя сеть добавлена, чтобы можно было проксировать или обращаться к приложениям по именам служб,
# прописанных в файлах docker-compose.yml этих приложений, если конечно эти приложения так же 
# входят в подсеть auth_proxy_network.
#  В противном случае придётся прописывать IP адреса приложений, 
# что неудобно при переносе приложений или их перезапуске. 
networks:
  default:
    external: true
    name: auth_proxy_network    