version: '3.1'

services:


  # база данных
  db:
    image: postgres:10.9-alpine
    container_name: auth-db
    restart: always
    # ports:
    #   - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: auth 
      PGDATA: /var/lib/postgresql/data/pgdata
  

  # сервер, где запущено приложение
  runner:
    image: rgru/auth-proxy
    container_name: auth-runner
    volumes:
      - test_apps:/go/src/auth-proxy/test_apps

    # раскомментируйте для SQLite вместо Postgres
    # command: bash -c "cd /go/src/auth-proxy && ./auth-proxy -serve 4400 -env=front -sqlite" 
    restart: always
    ports:
      - 4400:4400
    depends_on:
      - db
    links:
      - db


  # Сервер с тестовыми приложениями
  node:
    image: "node:alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - test_apps:/home/node/app
    expose:
      - "3001"
      - "3002"
      - "3003"
      - "3004"
      - "3005"
    # ports:
    #   - 3001:3001
    #   - 3002:3002
    #   - 3003:3003
    #   - 3004:3004
    #   - 3005:3005
    command: "npm run start12"


volumes: 
  test_apps:
