FROM ubuntu:18.04
LABEL maintainer="RGRU <ivlev@rg.ru>"

RUN apt-get -y update 
RUN apt-get -y install curl
# RUN apt-get -y install iputils-ping
# RUN apt-get -y install mc
# RUN apt-get -y install nodejs
# RUN apt-get -y install sqlite3 

COPY auth-proxy  /app/auth-proxy
COPY configs     /app/configs
COPY migrations  /app/migrations
COPY templates   /app/templates
COPY testapps   /app/testapps

EXPOSE 4400

CMD bash -c "cd /app && ./auth-proxy -serve 4400 -env=front"




