version: '3.1'

services:


  # база данных
  db:
    image: postgres
    container_name: auth-db
    restart: always
    # ports:
    #   - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: auth 
      PGDATA: /var/lib/postgresql/data/pgdata
  


  # сервер, где запущено приложение
  runner:
    image: rgru/auth-proxy
    container_name: auth-runner
    restart: always
    ports:
      - 4400:4400
    depends_on:
      - db
    links:
      - db



  # Раскомментируйте если хотите просматривать базу данных в браузере http://localhost:8080
  # adminer:
  #   image: adminer
  #   container_name: adminer-com
  #   # network_mode: bridge
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - db
  #   links:
  #     - db
