FROM golang:1.12.5-stretch 
LABEL maintainer="RGRU <ivlev@rg.ru>"

# RUN apt-get -y update && apt-get -y install sshpass 

WORKDIR /go/src/auth-proxy
COPY . .

ENV GO111MODULE=on

# RUN env CGO_ENABLED=0 go build
# ключи нужны для компиляции sqlite3 при CGO_ENABLED=1
RUN env CGO_ENABLED=1 go build -a -ldflags '-linkmode external -extldflags "-static"' 



EXPOSE 4400

CMD ["./auth-proxy", "-serve", "4400", "-env=front"]

