version: '3.1'

services:



  # сервер, где запущено приложение
  auth-proxy-front:
    image: rgru/auth-proxy:latest
    container_name: auth-proxy-front
    volumes:
      - test_apps:/app/node-apps

    # command: bash -c "cd /app && ./auth -serve 4400 -env=front" 
    restart: always
    ports:
      - 4400:4400
    depends_on:
      - db
    links:
      - db


  # server with test applications
  auth-node:
    image: "node:alpine"
    container_name: auth-node
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - test_apps:/home/node/app
    expose:
      - "3001"
      - "3002"
      - "3003"
      - "3004"
      - "3005"
    command: "npm run start12"


  # база данных
  auth-db:
    image: postgres:10.9-alpine
    container_name: auth-db
    restart: always
    # ports:
    #   - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: auth 
      PGDATA: /var/lib/postgresql/data/pgdata
  





volumes: 
  test_apps:
    