version: '3.9'

services:
  auth-proxy:
    image: ${REGISTRY}-${NODE_ENV}:${CI_PIPELINE_ID}
    env_file:
      - /builds/db_conf/${CI_PROJECT_NAME}-${NODE_ENV}/configs/env
    environment:
      PORT: ${PORT}      
      NODE_ENV: ${NODE_ENV}
      NODE_APP: ${NODE_APP}
    restart: always
    ports:
      - ${PORT}:${PORT}

networks:
  default:
    external:
      name: auth_proxy_network
