version: '3.1'

services:



  auth-node:
    image: "node:alpine"
    container_name: auth-node
    user: "node"
    working_dir: /home/node/app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./node-apps:/home/node/app
    ports:
      - 3001-3005:3001-3005
    command: /bin/sh -c 'cd /home/node/app && npm install && npm run start12'


  auth-db:
    image: postgres:10.9-alpine
    container_name: auth-db-dev
    restart: always
    ports:
      - 5432:5432
    # volumes:
    #   - "./pgdata:/var/lib/postgresql/data/pgdata"
    #   - "./migrations:/dumps"
    #   - "./etc/.pgpass:/root/.pgpass"
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: 159753
      POSTGRES_DB: rgru 
      PGDATA: /var/lib/postgresql/data/pgdata



# внешняя сеть добавлена, чтобы можно было проксировать или обращаться к приложениям по именам служб,
# прописанных в файлах docker-compose.yml этих приложений, если конечно эти приложения так же 
# входят в подсеть auth_proxy_network.
#  В противном случае придётся прописывать IP адреса приложений, 
# что неудобно при переносе приложений или их перезапуске. 
networks:
  default:
    external:
      name: auth_proxy_network    