# https://gist.github.com/subfuzion/08c5d85437d5d4f00e58


#  D I R E C T   R E Q U E S T S ============================================================

### POST urlencoded -------------------------
curl -d "param1=value1&param2=value2" -X POST http://localhost:3000/data

###    
POST http://localhost:3000/data/aaa/bbb HTTP/1.1
Content-Type: application/x-www-form-urlencoded

param1=value1
&param2=value2


### POST urlencoded -------------------------
curl -d '{"key1":"value1", "key2":"value2"}' -H "Content-Type: application/json" -X POST http://localhost:3000/data

###
POST http://localhost:3000/data HTTP/1.1
Content-Type: application/json

{
    "key1":"value1", 
    "key2":"value2"
}

### GET ---------------------
GET http://localhost:3000/data/aaa/bbb?param1=value1&param2=value2
###
curl 'http://localhost:3000/data?param1=value1&param2=value2'

###



#  P R O X I E D  ===============================================================

# ping
GET http://localhost:4000/ping


### direct GET
GET http://localhost:3000/apps/api/books/234?aaa=bbb
### proxied GET
GET http://localhost:4000/app1/api/books/234?aaa=bbb


### direct POST

POST http://localhost:3000/data/aaa/bbb HTTP/1.1
Content-Type: application/x-www-form-urlencoded

param1=value1
&param2=value2

### proxied POST

POST http://localhost:4000/app1/data/aaa/bbb HTTP/1.1
Content-Type: application/x-www-form-urlencoded

param1=value1
&param2=value2

###





