priorityclass:
  _default: "develop"
  stage: "staging"
  production: "production-medium"

app:
  port:
    _default: 4400
  resources:
    cpu:
      _default: "10m"
      production: "50m"
    memory:
      requests:
        _default: "16Mi"
        production: "128Mi"
      limits:
        _default: "16Mi"
        production: "128Mi"
  domain:
    _default: "lk-{{ .Values.werf.env }}.k8s.rg.ru"
    production: lk.rg.ru
  site_host:
    _default: "https://frontend-{{ .Values.werf.env }}.k8s.rg.ru"
    production: "https://rg.ru"
  proxy_body_size:
    _default: 128m
  tls:
    _default: false
  secure:
    _default: true
  selfreg:
    production: true
    _default: true
  login_not_confirmed_email:
    _default: false
  no_schema:
    production: true
    _default: false
  use_captcha:
    production: true
    _default: true
  use_pin:
    production: true
    _default: true
  max_attempts:
    _default: 5
  reset_time:
    _default: 60
  admin_api:
    _default: "https://lk-{{ .Values.werf.env }}.k8s.rg.ru"
    production: "https://lk.rg.ru"
  entry_point:
    production: "https://rg.ru/account/profile?email_success=true"
    _default: "https://frontend-{{ .Values.werf.env }}.k8s.rg.ru/account/profile?email_success=true"
  smtp_address:
    _default: mail4.rg.ru:25
  mail_from:
    _default: "noreply@rg.ru"
  admin_url:
    production: ""
    _default: "https://auth-admin.vercel.app/?url=https://lk-{{ .Values.werf.env }}.k8s.rg.ru"
  mail_tmpl_path:
    _default: "./templates/mail_lk"
  graphql_test_url:
    production: ""
    _default: "https://graphql-test.vercel.app/?end_point=https://lk-{{ .Values.werf.env }}.k8s.rg.ru/schema&tab_name=auth-proxy4400"
replicas:
  app:
    hpa:
      min_replicas:
        _default: 2 
      max_replicas:
        _default: 3
      averageUtilization:
        _default: 80

infra:
    pg:
      host:
        _default: 'postgres-lk.infra-{{ .Values.werf.env }}.svc.cluster.local'
        production: 'postgres-lk-master.infra-{{ .Values.werf.env }}.svc.cluster.local'
      user:
        _default: 'lk-{{ .Values.werf.env }}'
      port:
        _default: 5432
      sslmode:
        _default: 'disable'
      database:
        _default: 'lk-{{ .Values.werf.env }}'
      searchpath:
        _default: 'auth,extensions'

tolerations:
  _default: []
  production:
    - effect: "NoSchedule"
      key: dedicated.flant.com
      operator: "Equal"
      value: "production"

nodeaffinity:
  _default: {}
  production:
   requiredDuringSchedulingIgnoredDuringExecution:
    nodeSelectorTerms:
    - matchExpressions:
      - key: node-role.kubernetes.io/production
        operator: Exists

ingressClass:
  _default: nginx
  production: nginx-qurator