# Для окружений dev, front, prod
# устанавливает соответствие
# идентификатор приложения : URL приложения

dev:
  app1:     http://localhost:3001
  app2:     http://localhost:3002
  onlinebc: http://localhost:7700
  rg:       https://rg.ru 


front:
  app1:     http://node:3001
  app2:     http://node:3002
  onlinebc: http://onlinebc:7700
  rg:       https://rg.ru 


prod:
  app1:     http://localhost:3001
  app2:     http://localhost:3002
  onlinebc: http://localhost:7700
  rg:       https://rg.ru 
