version: '2.1'

services:

  # сервер, где запущено приложение
  auth-proxy-prod:
    image: auth-proxy-prod
    container_name: auth-proxy-prod
    restart: always
    dns:
      - '194.190.37.16'
      - '194.190.23.68'
    ports:
      - 4400:4400
    volumes: 
      - app-logs:/app/logs
      - ./configs:/app/configs
    command: bash -c "cd /app && ./auth-proxy -env=prod -serve=4400 2>/app/logs/auth-proxy.log"


  # server with test applications
  auth-node:
    image: "node:10.16-stretch-slim"
    container_name: auth-node
    user: "node"
    working_dir: /home/node/app
    depends_on: 
      - auth-proxy-prod
    environment:
      - NODE_ENV=production
    volumes:
      - ./node-apps:/home/node/app
    expose:
      - "3001"
      - "3002"
      - "3003"
      - "3004"
      - "3005"
    command: /bin/sh -c 'cd /home/node/app && npm install && chmod -Rf 777 node_modules && npm run start12 ; sleep 20000'

networks:
  default:
    external:
      name: auth_proxy_network

# Данные логов
volumes:
  app-logs:
    external: true
