version: '2.0'

services:


  # сервер, где запущено приложение
  auth-proxy-prod:
    image: auth-proxy-prod
    container_name: auth-proxy-prod
    volumes:
      - test_apps:/app/node-apps

    # command: bash -c "cd /app && ./auth -serve 4400 -env=prod" 
    restart: always
    ports:
      - 4400:4400




  # server with test applications
  auth-node:
    image: "node:10.16-stretch-slim"
    container_name: auth-node
    user: "node"
    working_dir: /home/node/app
    depends_on: 
      - auth-proxy-prod
    environment:
      - NODE_ENV=production
    volumes:
      - test_apps:/home/node/app
    expose:
      - "3001"
      - "3002"
      - "3003"
      - "3004"
      - "3005"
    command: /bin/sh -c 'cd /home/node/app && npm install && npm run start12 ; sleep 20000'


volumes: 
  test_apps:
    