# Шаблоны писем пользователям для различных случаев.

# Символы шаблонов %s не трогать.  
# Их должно быть 4, 2 в теле письма.

# Менять можно текст Subject после двоеточия
# и текст самого сообщения, отделенный от Subject пустой строкой.
# Каждая новая строка должна иметь отступ в два пробела.


# Новый пароль
new_password: |
  From: %s
  To: %s
  Subject: New password

  Это ваш новый пароль.

  Перейдите по ссылке %s и введите

  Имя пользователя: %s
  Новый пароль: %s

  С уважением,
  RG.RU

  Вопросы: dev@rg.ru


# Регистрация нового пользователя
new_user: |
  From: %s
  To: %s
  Subject: New user registration

  Вы зарегистрированы в системе редакторского интерфейса Года Литературы

  Перейдите по ссылке %s и введите

  Имя пользователя: %s
  Пароль: %s

  С уважением,
  RG.RU

  Вопросы: dev@rg.ru



reset_authenticator: |
  From: %s
  To: %s
  Subject: Reset authenticator

  Если не вы инициировали это письмо, игнорируйте его.

  Для установки аутентификатора Google на вашем телефоне
  перейдите по следующей ссылке и следуйте инструкциям.

  %s
 
  С уважением,
  RG.RU

  Вопросы: dev@rg.ru


reset_password: |
  From: %s
  To: %s
  Subject: Reset password

  Если не вы инициировали это письмо, игнорируйте его.

  Для установки пароля перейдите по следующей ссылке.

  %s
 
  С уважением,
  RG.RU

  Вопросы: dev@rg.ru

