# Местоположение сертификатов для цифровой подписи запросов
# к проксируемым приложениям.

front:
  private_key_file: ./certificates/auth-proxy.key
  public_key_file: ./certificates/auth-proxy.key.pub
  headers: ["(request-target)", "host", "date"]
  keyid: auth-proxy