version: '2.1'

services:

  # сервер, где запущено приложение
  auth-proxy-staging:
    image: auth-proxy-staging
    container_name: auth-proxy-staging
    restart: always
    ports:
      - 4402:4402


  # server with test applications
  # auth-node:
  #   image: "node:10.16-stretch-slim"
  #   container_name: auth-node
  #   user: "node"
  #   working_dir: /home/node/app
  #   depends_on: 
  #     - auth-proxy-staging
  #   environment:
  #     - NODE_ENV=production
  #   volumes:
  #     - ./node-apps:/home/node/app
  #   expose:
  #     - "3011"
  #     - "3012"
  #     - "3013"
  #     - "3014"
  #     - "3015"
  #   command: /bin/sh -c 'cd /home/node/app && npm install && chmod -Rf 777 node_modules && npm run start12 ; sleep 20000'

networks:
  default:
    external:
      name: auth_proxy_network