version: '2.1'

services:

  # сервер, где запущено приложение
  auth-proxy-staging:
    image: auth-proxy-staging
    container_name: auth-proxy-staging
    restart: always
    dns:
      - '194.190.37.16'
      - '194.190.23.68'
    ports:
      - 4402:4402



networks:
  default:
    external:
      name: auth_proxy_network