# Общие параметры приложения
# для окружений dev, front, prod

# изначально 
# были параметрами запуска приложения.
# Теперь перенесены в настроечные файлы для упрощения запуска приложения


dev:
  # Имя приложения. Используется для генерации PIN Google Authenticator
  app_name: auth-proxy-dev
  # Использовать https вместо http
  tls: true
  # Установить флаг secure на куки браузера. Работает только для https протокола.
  secure: true
  # Пользователи могут регистрироваться самостоятельно
  selfreg: true
  # Нужно ли вводить капчу при входе в систему
  use_captcha: true
  # Нужно ли вводить PIN при входе в систему
  use_pin: true
  # Максимально допустимое число ошибок ввода пароля
  max_attempts: 5
  # Время сброса счетчика ошибок пароля в минутах
  reset_time: 60

  # перенаправления браузера для предоставления различных GUI 
  redirects:
    # админка сервиса. 
    /admin-local:   http://localhost:5000/?url=https://localhost:4400
    /admin: https://auth-admin.vercel.app/?url=https://localhost:4400
    /admin-test: https://auth-admin-test.vercel.app/?url=https://localhost:4400
    # тест GraphQL API. 
    /test: https://graphql-test.vercel.app/?end_point=https://localhost:4400/schema&tab_name=auth-proxy4400


front:
  # Имя приложения. Используется для генерации PIN Google Authenticator
  app_name: auth-proxy-front
  # Использовать https вместо http
  tls: true
  # Установить флаг secure на куки браузера. Работает только для https протокола.
  secure: true
  # Пользователи могут регистрироваться самостоятельно
  selfreg: false
  # Нужно ли вводить капчу при входе в систему
  use_captcha: true
  # Нужно ли вводить PIN при входе в систему
  use_pin: false
  # Максимально допустимое число ошибок ввода пароля
  max_attempts: 5
  # Время сброса счетчика ошибок пароля в минутах
  reset_time: 60

  # перенаправления браузера для предоставления различных GUI 
  redirects:
    # админка сервиса. 
    /admin:   https://auth-admin.vercel.app/?url=https://localhost:4400
    /testapp: https://auth-admin.vercel.app/?url=https://localhost:4400
    # тест GraphQL API. 
    /test: https://graphql-test.vercel.app/?end_point=https://localhost:4400/schema&tab_name=auth-proxy4400

public:
  # Имя приложения. Используется для генерации PIN Google Authenticator
  app_name: auth-proxy-public
  # Использовать https вместо http
  tls: true
  # Установить флаг secure на куки браузера. Работает только для https протокола.
  secure: true
  # Пользователи могут регистрироваться самостоятельно
  selfreg: true
  # Нужно ли вводить капчу при входе в систему
  use_captcha: true
  # Нужно ли вводить PIN при входе в систему
  use_pin: false
  # Максимально допустимое число ошибок ввода пароля
  max_attempts: 10
  # Время сброса счетчика ошибок пароля в минутах
  reset_time: 30

  # перенаправления браузера для предоставления различных GUI 
  redirects:
    # админка сервиса. 
    /admin:   https://auth-admin.vercel.app/?url=https://localhost:4400
    /testapp: https://auth-admin.vercel.app/?url=https://localhost:4400
    # тест GraphQL API. 
    /test: https://graphql-test.vercel.app/?end_point=https://localhost:4400/schema&tab_name=auth-proxy4400
