# Параметры подключения к Postgres
# для окружений dev, front

dev:
  host:     localhost
  user:     root
  password: root
  database: auth
  port:     5432
  search_path: auth,extensions
  sslmode:  disable

front:
  host:     postgres
  user:     pgadmin
  password: 159753
  database: rgru
  port:     5432
  search_path: auth,extensions
  sslmode:  disable