# Параметры подключения к базе данных
# для окружений dev, docker, prod


dev:
  host: localhost
  port: 5432
  user: root 
  password: root 
  dbname: auth 
  sslmode: disable
  sqlite: ./auth.db


docker:
  host: db
  port: 5432
  user: root 
  password: root 
  dbname: auth 
  sslmode: disable
  sqlite: ./auth.db


prod:
  host: localhost
  port: 5432
  user: root 
  password: root 
  dbname: auth 
  sslmode: disable
  sqlite: ./auth.db
