# Параметры подключения к Postgres
# для окружений dev, front, prod


dev:
  host: localhost
  user: root 
  password: root 
  database: auth 
  port: 5432
  sslmode: disable


front:
  host: db
  user: root 
  password: root 
  database: auth 
  port: 5432
  sslmode: disable


prod:
  host: localhost
  user: root 
  password: root 
  database: auth 
  port: 5432
  sslmode: disable
