# Шаблоны писем пользователям для различных случаев.

# Символы шаблонов %s не трогать.  
# Их должно быть 4, 2 в теле письма.

# Менять можно текст Subject после двоеточия
# и текст самого сообщения, отделенный от Subject пустой строкой.
# Каждая новая строка должна иметь отступ в два пробела.


# Новый пароль
new_password: |
  From: %s
  To: %s
  Subject: Новый пароль

  Это ваш новый пароль.

  Перейдите по ссылке https://auth-proxy.rg.ru/admin и введите

  Имя пользователя: %s
  Новый пароль: %s

  С уважением,
  RG.RU

  Вопросы: dev@rg.ru


# Регистрация нового пользователя
new_user: |
  From: %s
  To: %s
  Subject: Регистрация нового пользователя

  Вы зарегистрированы в auth-proxy.rg.ru

  Перейдите по ссылке https://auth-proxy.rg.ru/admin и введите

  Имя пользователя: %s
  Пароль: %s

  С уважением,
  RG.RU

  Вопросы: dev@rg.ru


# Пин для двухфакторной авторизации
new_pin: |
  From: %s
  To: %s
  Subject: Пин для авторизации

  Это ваш пин код.

  Перейдите по ссылке https://auth-proxy.rg.ru/admin и введите

  Имя пользователя: %s
  Пин: %s

  С уважением,
  RG.RU

  Вопросы: dev@rg.ru

