# Параметры подключения к почтовому серверу
# для окружений dev, front, prod


dev:
  addr: mail3.rg.ru:25
  from: noreply@rg.ru
  # Тело сообщения можно менять.
  # Символы шаблонов %s не трогать.  
  # Их должно быть 4, 2 в теле письма.
  body: |
    From: %s
    To: %s
    Subject: New password

    Имя пользователя: %s
    Новый пароль: %s

    С уважением,
    RG.RU
    

front:
  addr: mail3.rg.ru:25
  from: noreply@rg.ru
  # Тело сообщения можно менять.
  # Символы шаблонов %s не трогать.  
  # Их должно быть 4, 2 в теле письма.
  body: |
    From: %s
    To: %s
    Subject: New password

    Имя пользователя: %s
    Новый пароль: %s

    С уважением,
    RG.RU
        

prod:
  addr: mail3.rg.ru:25
  from: noreply@rg.ru
  # Тело сообщения можно менять.
  # Символы шаблонов %s не трогать.  
  # Их должно быть 4, 2 в теле письма.
  body: |
    From: %s
    To: %s
    Subject: New password

    Имя пользователя: %s
    Новый пароль: %s

    С уважением,
    RG.RU
    

   

