# Параметры подключения к почтовому серверу
# для окружений dev, front, prod

dev:
  addr: mail3.rg.ru:25
  from: noreply@rg.ru
  link: https://auth-proxy.rg.ru/admin
    
front:
  addr: mail3.rg.ru:25
  from: noreply@rg.ru
  link: https://auth-proxy.rg.ru/admin

public:
  addr: mail3.rg.ru:25
  from: noreply@rg.ru
  link: https://auth-proxy.rg.ru/admin