# Параметры подключения к почтовому серверу

dev:
  smtp_address: localhost:1025
  from: noreply@rg.ru
  confirm_email_url: https://localhost:4400/confirm-email/
  entry_point: https://www.rg.ru
    
front:
  smtp_address: mail3.rg.ru:25
  from: noreply@rg.ru
  confirm_email_url: https://localhost:4400/confirm-email/
  entry_point: https://www.rg.ru

public:
  smtp_address: mail3.rg.ru:25
  from: noreply@rg.ru
  confirm_email_url: https://auth-proxy.rg.ru/confirm-email/
  entry_point: https://www.rg.ru