# Общие параметры приложения
# для окружений dev, front, prod

# изначально 
# были параметрами запуска приложения.
# Теперь перенесены в настроечные файлы для упрощения запуска приложения

dev:
  # Имя приложения. Используется для генерации PIN Google Authenticator
  app_name: auth-proxy-rg-dev
  # Использовать https вместо http
  tls: true
  # Установить флаг secure на куки браузера. Работает только для https протокола.
  secure: true
  # Пользователи могут регистрироваться самостоятельно
  selfreg: true
  # Нужно ли вводить капчу при входе в систему
  use_captcha: true
  # Нужно ли вводить PIN при входе в систему
  use_pin: false
  # Максимально допустимое число ошибок ввода пароля
  max_attempts: 5
  # Время сброса счетчика ошибок пароля в минутах
  reset_time: 60

  # url страницы подтверждения email
  confirm_email_url: https://localhost:4400/confirm-email/
  # url куда пренаправляется браузер после подтвержедения email
  entry_point: https://www.rg.ru
  # адрес почтового сервера SMTP
  smtp_address: localhost:1025
  # email от которого посылаются письма пользователям
  from: noreply@rg.ru
  # админка сервиса. 
  admin_url:   https://localhost:5000/?url=https://localhost:4400
  # тестовая страница сервиса
  graphql_test_url: https://graphql-test.vercel.app/?end_point=https://localhost:4400/schema&tab_name=auth-proxy4400


front:
  # Имя приложения. Используется для генерации PIN Google Authenticator
  app_name: auth-proxy-rg-front
  # Использовать https вместо http
  tls: true
  # Установить флаг secure на куки браузера. Работает только для https протокола.
  secure: true
  # Пользователи могут регистрироваться самостоятельно
  selfreg: false
  # Нужно ли вводить капчу при входе в систему
  use_captcha: true
  # Нужно ли вводить PIN при входе в систему
  use_pin: false
  # Максимально допустимое число ошибок ввода пароля
  max_attempts: 5
  # Время сброса счетчика ошибок пароля в минутах
  reset_time: 60

  # url страницы подтверждения email
  confirm_email_url: https://localhost:4400/confirm-email/
  # url куда пренаправляется браузер после подтвержедения email
  entry_point: https://www.rg.ru
  # адрес почтового сервера SMTP
  smtp_address: localhost:1025
  # email от которого посылаются письма пользователям
  from: noreply@rg.ru
  # админка сервиса. 
  admin_url:   https://auth-admin.vercel.app/?url=https://localhost:4400
  # тестовая страница сервиса
  graphql_test_url: https://graphql-test.vercel.app/?end_point=https://auth-proxy.rg.ru/schema&tab_name=auth-proxy

staging:
  # Имя приложения. Используется для генерации PIN Google Authenticator
  app_name: auth-proxy-rg-staging
  # Использовать https вместо http
  tls: false
  # Установить флаг secure на куки браузера. Работает только для https протокола. 
  # На продакшене установлен в true, не смотря на tls: false.
  # Так как приложение проксируется через отдельный сервер со своим TLS
  secure: true
  # Пользователи могут регистрироваться самостоятельно
  selfreg: false
  # Нужно ли вводить капчу при входе в систему
  use_captcha: true
  # Нужно ли вводить PIN при входе в систему
  use_pin: true
  # Максимально допустимое число ошибок ввода пароля
  max_attempts: 5
  # Время сброса счетчика ошибок пароля в минутах
  reset_time: 60
  
  # url страницы подтверждения email
  confirm_email_url: https://auth-proxy.rg.ru/confirm-email/
  # url куда пренаправляется браузер после подтвержедения email
  entry_point: https://www.rg.ru
  # адрес почтового сервера SMTP
  smtp_address: mail3.rg.ru:25
  # email от которого посылаются письма пользователям
  from: noreply@rg.ru
  # админка сервиса. 
  admin_url:   https://auth-admin.vercel.app/
  # тестовая страница сервиса
  graphql_test_url: https://graphql-test.vercel.app/?end_point=https://auth-proxy.rg.ru/schema&tab_name=auth-proxy

prod:
  # Имя приложения. Используется для генерации PIN Google Authenticator
  app_name: auth-proxy-rg
  # Использовать https вместо http
  tls: false
  # Установить флаг secure на куки браузера. Работает только для https протокола. 
  # На продакшене установлен в true, не смотря на tls: false.
  # Так как приложение проксируется через отдельный сервер со своим TLS
  secure: true
  # Пользователи могут регистрироваться самостоятельно
  selfreg: false
  # Нужно ли вводить капчу при входе в систему
  use_captcha: true
  # Нужно ли вводить PIN при входе в систему
  use_pin: true
  # Максимально допустимое число ошибок ввода пароля
  max_attempts: 5
  # Время сброса счетчика ошибок пароля в минутах
  reset_time: 60
  
  # url страницы подтверждения email
  confirm_email_url: https://auth-proxy.rg.ru/confirm-email/
  # url куда пренаправляется браузер после подтвержедения email
  entry_point: https://www.rg.ru
  # адрес почтового сервера SMTP
  smtp_address: mail3.rg.ru:25
  # email от которого посылаются письма пользователям
  from: noreply@rg.ru
  # админка сервиса. 
  admin_url:   https://auth-admin.vercel.app/
  # тестовая страница сервиса
  graphql_test_url: https://graphql-test.vercel.app/?end_point=https://auth-proxy.rg.ru/schema&tab_name=auth-proxy

