# Шаблоны писем пользователям для различных случаев.

# Символы шаблонов %s не трогать.  
# Их должно быть 4, 2 в теле письма.

# Менять можно текст Subject после двоеточия
# и текст самого сообщения, отделенный от Subject пустой строкой.
# Каждая новая строка должна иметь отступ в два пробела.




# Регистрация нового пользователя
# Параметр redirect указывает на страницу куда перейдет пользователь
# после подтверждения email. 
# Меняйте только текст и значение redirect=
new_user: |
  From: %s
  To: %s
  Subject: New user Email confirmation

  Вы зарегистрированы в системе редакторского интерфейса RG.RU.
  Чтобы подтвердить Ваш Email перейдите по ссылке:

  %s?%s

  С уважением,
  RG.RU

  Вопросы: dev@rg.ru



reset_authenticator: |
  From: %s
  To: %s
  Subject: Reset authenticator

  Если не вы инициировали это письмо, игнорируйте его.

  Для установки аутентификатора Google на вашем телефоне
  перейдите по следующей ссылке и следуйте инструкциям.

  %s
 
  С уважением,
  RG.RU

  Вопросы: dev@rg.ru


reset_password: |
  From: %s
  To: %s
  Subject: Reset password

  Если не вы инициировали это письмо, игнорируйте его.

  Для установки пароля перейдите по следующей ссылке.

  %s
 
  С уважением,
  RG.RU

  Вопросы: dev@rg.ru

