{{- if eq .Values.werf.env "production" }}
---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: {{ .Chart.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Chart.Name }}
  minReplicas: {{ pluck .Values.werf.env $.Values.replicas.app.hpa.min_replicas | first | default .Values.replicas.app.hpa.min_replicas._default }}
  maxReplicas: {{ pluck .Values.werf.env $.Values.replicas.app.hpa.max_replicas | first | default .Values.replicas.app.hpa.max_replicas._default }}
  metrics:
  - type: Pods
    pods:
      metric:
        name: {{ .Chart.Name }}
      target:
        type: AverageValue
        averageValue: 80
{{- end }}
