---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: {{ pluck .Values.werf.env .Values.app.proxy_body_size | first | default .Values.app.proxy_body_size._default }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      gzip off;
      add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
spec:
  rules:
  - host: {{ tpl (pluck .Values.werf.env .Values.app.domain | first | default .Values.app.domain._default) . }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Chart.Name }}
            port:
              name: http
  tls:
  - hosts:
      - {{ tpl (pluck .Values.werf.env .Values.app.domain | first | default .Values.app.domain._default) . }}
{{- if ne .Values.werf.env "production" }}
    secretName: {{ .Chart.Name }}-tls
{{- else }}
    secretName: rg-tls
{{- end }}

{{- if ne .Values.werf.env "production" }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Chart.Name }}
spec:
  secretName: {{ .Chart.Name }}-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  dnsNames:
    - {{ tpl (pluck .Values.werf.env .Values.app.domain | first | default .Values.app.domain._default) . }}
{{- end }}
